# Generated by Django 3.0.7 on 2020-09-16 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperonizza', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('p', 'pending'), ('a', 'Accepted'), ('d', 'Decline')], max_length=50),
        ),
    ]
