# Generated by Django 3.0.7 on 2020-10-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperonizza', '0002_auto_20200916_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='profile_pic',
            field=models.ImageField(default='Null', upload_to='pics'),
        ),
    ]
