# Generated by Django 3.0.7 on 2020-10-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pepperonizza', '0004_auto_20201024_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermodel',
            name='username',
            field=models.CharField(default='null', max_length=150),
            preserve_default=False,
        ),
    ]
